name: scan_barcode_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+18

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  modal_bottom_sheet: ^3.0.0
  go_router: ^14.0.1
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  dotted_border: ^2.1.0
  money_formatter: ^0.0.5
  file_picker: ^8.1.7
  image_picker: ^1.1.1
  lottie: ^3.1.0
  flutter_slidable: ^3.1.2
  awesome_dialog: ^3.2.1
  mobile_scanner: ^5.1.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_otp_text_field: ^1.1.3+2
  local_auth: ^2.2.0
  country_flags: ^2.2.0
  animated_bottom_navigation_bar: ^1.3.3
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  easy_stepper: ^0.8.5
  signature: ^5.5.0
  barcode_widget: ^2.0.4
  fluttertoast: ^8.2.6
  flutter_cached_pdfview: ^0.4.2
  connectivity_plus: ^6.0.3
  flutter_bloc: ^8.1.6
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  gal: ^2.3.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.2.8
  percent_indicator: ^4.2.3
  carousel_slider_plus: ^7.0.0
  motion_toast: ^2.11.0
  flutter_html: ^3.0.0-beta.2
  timeline_tile: ^2.0.0
  avatar_glow: ^3.0.1
  google_mlkit_text_recognition: ^0.14.0
  camera: ^0.11.0+2
  flutter_file_dialog: ^3.0.2
  flutter_local_notifications: ^18.0.1
  flutter_localization: ^0.3.1
  flutter_widget_from_html: ^0.16.0
  google_ml_kit: ^0.19.0
  image: ^4.5.3
  flutter_tesseract_ocr: ^0.4.28
  font_awesome_flutter: ^10.8.0
  timeago: ^3.7.0
  flutter_quill: ^11.1.0
  flutter_quill_extensions: ^11.0.0
  dart_quill_delta: ^10.8.3
  tflite_flutter: ^0.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconApp.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/tessdata_config.json
    - assets/tessdata/digits.traineddata
    - assets/tessdata/eng.traineddata
    - assets/tessdata/OCRB.traineddata
    - assets/tessdata/7seg.traineddata
    - assets/tessdata/letsgodigital.traineddata
    - assets/yolo/yolov5s-fp16.tflite
  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
